databases:
  - name: foam_ai
    databaseName: foam_ai
    user: foam_ai
    plan: free

services:
  - type: web
    name: foam_ai
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foam_ai
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2

  - type: worker
    name: foam_ai-cron
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec whenever --update-crontab && cron -f"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foam_ai
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
